spring:
  application:
    name: orders-service
  data:
    mongodb:
      uri: mongodb+srv://alanvlins_db_user:pfQIBhVjhlQHUTOw@order-events.j3jnxmd.mongodb.net/orders_db?retryWrites=true&w=majority
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
